In [133]:
#연습문제 1
sp.stats.binom_test(2, 10), sp.stats.binom_test(1, 10)

(0.10937500000000003, 0.021484374999999997)

In [134]:
#연습문제 1
sp.stats.binom_test(8, 10), sp.stats.binom_test(9, 10)

(0.10937500000000003, 0.021484374999999997)

In [135]:
#연습문제 2
sp.stats.binom_test(474, 1000), sp.stats.binom_test(473, 1000)

(0.10674954203435372, 0.09368729147551143)

In [136]:
sp.stats.binom_test(526, 1000), sp.stats.binom_test(527, 1000)

(0.10674954203435372, 0.09368729147551143)

In [137]:
tips = sns.load_dataset("tips")
tips.tail()

total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [138]:
%matplotlib inline

In [139]:
a[a["smoker"] == "yes"].count()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
count         0
dtype: int64

In [140]:
smoker = a.groupby("smoker").count()
n

array([37, 32, 20, 11], dtype=int64)

In [141]:
n = 54
t = 87
sp.stats.binom_test(n, t)

0.031418110233846136

In [142]:
a[a["time"] == "Dinner"]["smoker"].count()

52

In [143]:
N = 10
K = 4
theta_0 = np.array([0.35, 0.30, 0.20, 0.15])
np.random.seed(0)
x = np.random.choice(K, N, p=theta_0)
n = np.bincount(x, minlength=K)
n

array([37, 32, 20, 11], dtype=int64)

In [144]:
sp.stats.chisquare(n)

Power_divergenceResult(statistic=16.56, pvalue=0.0008703471978912127)

In [145]:
n = [10, 0, 0, 0,]
sp.stats.chisquare(n)

Power_divergenceResult(statistic=30.0, pvalue=1.3800570312932553e-06)

In [146]:
import seaborn as sns
tips = sns.load_dataset("tips")
tips.pivot_table(index="sex", columns="day", aggfunc="size")

day     Thur  Fri  Sat  Sun
sex                        
Male      30   10   59   58
Female    32    9   28   18

In [148]:
obs = np.array([[30, 10, 59, 58], [32, 9, 28, 18]])
sp.stats.chi2_contingency(obs)

(13.22200137240661,
 0.004180302092822257,
 3,
 array([[39.89344262, 12.22540984, 55.9795082 , 48.90163934],
        [22.10655738,  6.77459016, 31.0204918 , 27.09836066]]))

p-value는 0.418%이므로 성별에 따라 달라진다고 할 수 있다

In [149]:
c1 = np.array([80, 75, 85, 50, 60, 75, 45, 70, 90, 95, 85, 80])
c2 = np.array([80, 85, 70, 80, 35, 55, 80])

In [151]:
sp.stats.ttest_ind(c1, c2, equal_var=True)

Ttest_indResult(statistic=0.623010926550264, pvalue=0.5415458608473267)