##### 인덱싱, ndim, shape, dtype

In [1]:
import numpy as np
# ndarray(N-dimensional Array) : 다차원 배열 자료구조를 지원

- array : 모든 원소가 같은 자료형, 접근과 반복문 실행이 빠름 -> 리스트와 차이점
- 원소의 갯수를 바꿀 수 없음

In [2]:
data = [0,1,2,3,4,5,6,7,8,9]
x = np.array(data) * 2
xx = data * 2
print(x, type(x))
print(xx, type(xx))

[ 0  2  4  6  8 10 12 14 16 18] <class 'numpy.ndarray'>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9] <class 'list'>


- NumPy는 1차원 배열 객체도 대부분 벡터로 인정하지만 그래도 열 개수가 1개인 2차원 벡터로 선언하는 것이 좋음
- Scikit-learn 패키지에서 벡터를 요구하는 경우에는 반드시 열의 개수가 1개인 2차원 배열 객체를 넣어야 함

In [3]:
x1 = np.array([[5.1], [3.5], [1.4], [0.2]])
x1

array([[5.1],
       [3.5],
       [1.4],
       [0.2]])

In [4]:
# 연습문제 1
x2 = np.array([[4.9], [3.0], [1.4], [0.2]])
x2

array([[4.9],
       [3. ],
       [1.4],
       [0.2]])

In [5]:
# np.array로 행렬 표현
A = np.array([[11, 12, 13], [21, 22, 23]])
A

array([[11, 12, 13],
       [21, 22, 23]])

In [6]:
# 연습문제 2
X = np.array([[5.1, 3.5, 1.4, 0.2], [4.9, 3.0, 1.4, 0.2]])
X, X.ndim   #2*3 matrix(2차원 배열)

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2]]), 2)

In [7]:
#3차원 배열 (2*3*4 matrix)
array = np.array([[[0,1,2,3], [4,5,6,7], [8,9,10,11]], [[0,1,2,3],[4,5,100,7],[8,9,10,11]]])
array, array.ndim, array.shape

(array([[[  0,   1,   2,   3],
         [  4,   5,   6,   7],
         [  8,   9,  10,  11]],
 
        [[  0,   1,   2,   3],
         [  4,   5, 100,   7],
         [  8,   9,  10,  11]]]), 3, (2, 3, 4))

In [30]:
array[:,[2,0,1],:]

array([[[  8,   9,  10,  11],
        [  0,   1,   2,   3],
        [  4,   5,   6,   7]],

       [[  8,   9,  10,  11],
        [  0,   1,   2,   3],
        [  4,   5, 100,   7]]])

In [8]:
#행렬 모양 변경
na = np.array([1,2,3,4,5,6,7,8])
print(na)
print(na.reshape(2, 4))

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


In [9]:
rna = np.reshape(na, (4, 2))
rna

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [10]:
#인덱싱
a = array[:,:,0]
a, a.ndim, a.shape

(array([[0, 4, 8],
        [0, 4, 8]]), 2, (2, 3))

In [11]:
array[0], array[0].ndim, array[0].shape

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), 2, (3, 4))

NumPy 배열 > 연습문제 2
#### 연습 문제 2¶
다음 행렬과 같은 행렬이 있다.

m = np.array([[ 0,  1,  2,  3,  4],
              [ 5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14]])
1. 이 행렬에서 값 7 을 인덱싱한다.
2. 이 행렬에서 값 14 을 인덱싱한다.
3. 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
4. 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
5. 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.

In [12]:
m = np.array([[0,1,2,3,4,],[5,6,7,8,9],[10,11,12,13,14]])
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
m[1, 2], m[-1, -1], m[1,1:3], m[1:, 2], m[:2, 3:]

(7, 14, array([6, 7]), array([ 7, 12]), array([[3, 4],
        [8, 9]]))

- 배열 인덱싱(array indexing, fancy indexing) : 대괄호 안의 인덱스 정보로 숫자나 슬라이스가 아니라 위치 정보를 나타내는 또다른 ndarray배열을 받을 수 있음
    - 불리안(boolean)배열 방식 : 인덱스 배열의 크기가 원래 ndarray객체 크기와 같아야 함
    - 정수배열 방식

In [14]:
#불리안 배열 방식
a = np.array([0,1,2,3,4,5,6,7,8,9])
idx = np.array([True, False, True, False, True, False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [15]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

In [16]:
#정수 배열방식
b = np.array([11,22,33,44,55,66,77,88,99])
idx = np.array([0,0,2,4,6,8])
b[idx]

array([11, 11, 33, 55, 77, 99])

In [17]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
a[:, [True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [19]:
a[[2,0,1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

#### 연습 문제 3¶
다음 행렬과 같은 배열이 있다.

x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
              11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
1. 이 배열에서 3의 배수를 찾아라.
2. 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
3. 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.

In [20]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
              11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [21]:
a = x[x % 3 ==0]
b = x[x % 4 == 1]
a, b

(array([ 3,  6,  9, 12, 15, 18]), array([ 1,  5,  9, 13, 17]))

In [22]:
x[np.any(a == b)]

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


array([], shape=(0, 20), dtype=int32)

In [24]:
# 데이터 유형 지정
x = np.array([1,2,3])
x, x.dtype

(array([1, 2, 3]), dtype('int32'))

In [27]:
y = np.array([1,2,3], dtype="f")
y

array([1., 2., 3.], dtype=float32)

- 접두사 	 설명 	 사용 예
- b 	 불리언 	 b (참 혹은 거짓)
- i 	 정수 	 i8 (64비트)
- u 	 부호 없는 정수 	 u8 (64비트)
- f 	 부동소수점 	 f8 (64비트)
- c 	 복소 부동소수점 	 c16 (128비트)
- O 	 객체 	 0 (객체에 대한 포인터)
- S 	 바이트 문자열 	 S24 (24 글자)
- U 	 유니코드 문자열 	 U24 (24 유니코드 글자)