- numpy random.seed / 어떤 특정한 시작 숫자를 정해주어 난수를 발생, 그 다음에 만들어지는 난수
- numpy random.rand / 0과 1사이 무작위로 난수 생성
- numpy random.shuffle / 데이터의 순서 바꾸기
- numpy random.choice / 샘플링, 데이터 집합에서 일부를 무작위로 선택함
##### numpy rand,randn,randint / 난수생성
- numpy.random.randn / 기댓값이 0이고 표준편차가 1인 가우시안 표준 정규 분포를 따르는 난수를 생성
- numpy.random.randint / numpy.random.randint(low, high=None, size=None)
##### numpy unique, bincount / 난수가 정수 값이라면 데이터 값 분석
- numpy.bincount / bincount에 minlength를 설정하여 0부터 minlength-1까지 숫자에 대해 각 카운트 한다.
- random.randrange(x,y) / x부터 y까지의 숫자를 random하게 뽑는다
- numpy random.normal / 정규분포로부터 무작위 샘플을 만듬
- numpy random.binomial / 이항분포로부터 무작위 표본 추출
- numpy random.poisson / 포아송분포로부터 무작위 표본 추출

seed : 어떤 특정한 시작 숫자를 정해 주면 컴퓨터가 정해진 알고리즘에 의해 마치 난수처럼 보이는 수열을 생성하는데, 이런 시작 숫자를 시드(seed)라고 한다. 일단 생성된 난수는 다음번 난수 생성을 위한 시드값이 된다. 따라서 시드값은 한 번만 정해주면 된다. 

In [1]:
np.random.seed(100)
rd = np.random.rand(10)     #uniform(균등분포)로 난수 발생
rdn = np.random.randn(10)   #gaussian(정규분포)로 난수 발생
rd, rdn

(array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886,
        0.12156912, 0.67074908, 0.82585276, 0.13670659, 0.57509333]),
 array([-0.18949583,  0.25500144, -0.45802699,  0.43516349, -0.58359505,
         0.81684707,  0.67272081, -0.10441114, -0.53128038,  1.02973269]))

In [2]:
rd = np.random.rand(2, 3)     #uniform(균등분포)로 난수 발생
rdn = np.random.randn(3, 3)   #gaussian(정규분포)로 난수 발생
rd, rdn

(array([[0.17541045, 0.37283205, 0.00568851],
        [0.25242635, 0.79566251, 0.01525497]]),
 array([[ 1.61898166,  1.54160517, -0.25187914],
        [-0.84243574,  0.18451869,  0.9370822 ],
        [ 0.73100034,  1.36155613, -0.32623806]]))

In [3]:
a = np.random.randint(1, 11, (3, 4))
a

array([[ 4,  6,  1, 10],
       [ 4,  7,  4,  5],
       [ 8,  7,  4, 10]])

In [4]:
np.random.shuffle(a)
a

array([[ 4,  7,  4,  5],
       [ 8,  7,  4, 10],
       [ 4,  6,  1, 10]])

numpy.random.choice(a, size=None, replace=True, p=None)

- a : 배열이면 원래의 데이터, 정수이면 range(a) 명령으로 데이터 생성
- size : 정수. 샘플 숫자
- replace : 불리언. True이면 한번 선택한 데이터를 다시 선택 가능
- p : 배열. 각 데이터가 선택될 수 있는 확률

In [5]:
np.random.choice(5, 10, replace=True, p=[0.1, 0, 0.3, 0.6, 0])

array([2, 2, 0, 3, 2, 3, 3, 2, 3, 3], dtype=int64)

In [6]:
# np.unique : 중복된 요소 제거
np.unique(a)

array([ 1,  4,  5,  6,  7,  8, 10])

In [7]:
index, count = np.unique(a, return_counts=True)
index, count    #return_counts 옵션은 요소의 개수

(array([ 1,  4,  5,  6,  7,  8, 10]),
 array([1, 4, 1, 1, 2, 1, 2], dtype=int64))

In [8]:
u = np.array(['a', 'b', 'b', 'c', 'a'])
index, count = np.unique(u, return_counts=True)
index, count

(array(['a', 'b', 'c'], dtype='<U1'), array([2, 2, 1], dtype=int64))

In [9]:
# 요소의 개수, 요소에 없어도 minlength를 통해 0값을 return
np.bincount([1, 1, 2, 2, 2, 3], minlength=6)

array([0, 2, 3, 1, 0, 0], dtype=int64)

#### split
np.split(<인수>, [n]) : n번째 뒤에서 분리

In [10]:
r = np.arange(0, 10)
r1 = np.split(r, [5])
r1

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [11]:
r2, r3 = np.split(r, [5])
print(r2, r3, sep="\n")

[0 1 2 3 4]
[5 6 7 8 9]


In [12]:
# vsplit
r = np.random.randint(10, size=(4, 6))
r

array([[0, 7, 2, 3, 5, 4],
       [2, 4, 3, 7, 9, 0],
       [0, 5, 9, 6, 6, 5],
       [6, 4, 7, 3, 9, 2]])

In [13]:
r1, r2, r3 = np.vsplit(r, [2, 3])
print(r1, r2, r3, sep="\n")

[[0 7 2 3 5 4]
 [2 4 3 7 9 0]]
[[0 5 9 6 6 5]]
[[6 4 7 3 9 2]]


In [14]:
h1, h2, h3 = np.hsplit(r, [2, 4])
print(h1, h2, h3, sep="\n")

[[0 7]
 [2 4]
 [0 5]
 [6 4]]
[[2 3]
 [3 7]
 [9 6]
 [7 3]]
[[5 4]
 [9 0]
 [6 5]
 [9 2]]


#### sort : 행이나 열 내에서 정렬

In [15]:
s1 = np.random.randint(10, size=(3,3))
s1

array([[3, 8, 7],
       [1, 5, 9],
       [3, 0, 6]])

In [16]:
s1.sort()
s1

array([[3, 7, 8],
       [1, 5, 9],
       [0, 3, 6]])

In [17]:
s2 = np.random.randint(10, size=(3,3))
s2

array([[2, 3, 4],
       [8, 9, 8],
       [5, 2, 7]])

In [18]:
np.sort(s2, axis=0)

array([[2, 2, 4],
       [5, 3, 7],
       [8, 9, 8]])

In [19]:
s2.sort(axis=-1)
s2

array([[2, 3, 4],
       [8, 8, 9],
       [2, 5, 7]])

In [20]:
s3 = np.random.randint(1, 20, size=(3, 4, 5))
s3

array([[[13,  1, 10,  9,  3],
        [17,  6,  3,  4, 15],
        [14,  2, 15,  2,  9],
        [19, 19,  8,  3, 18]],

       [[ 3, 18, 14,  1, 11],
        [ 4,  6, 19,  7, 18],
        [11, 14, 18,  3, 16],
        [13, 12,  6, 13,  7]],

       [[17, 19, 18,  2, 11],
        [13, 17,  5, 11,  6],
        [17, 17, 18,  4,  3],
        [ 4, 18, 17,  7,  3]]])

In [21]:
np.sum(s3, axis=1)

array([[63, 28, 36, 18, 45],
       [31, 50, 57, 24, 52],
       [51, 71, 58, 24, 23]])

(3, 4, 5)인 3차원 배열일 경우 axis=(0, -1, 1)

(3, 4)인 2차원 배열일 경우 axis=(-1 | 1, 0)

In [22]:
# 요소에 대한 순서만 알고 싶을 때
# argsort():정렬을 한 후 그 자리에 와야 하는 요소의 현재 위치 출력
a = np.array([42, 38, 12, 16])
np.argsort(a), a[a.argsort()]

(array([2, 3, 1, 0], dtype=int64), array([12, 16, 38, 42]))

#### 연습 문제 2¶
다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은 배열이다. 영어 성적을 기준으로 각 열(column)을 재정렬하라.

array([[  1,    2,    3,    4],
       [ 46,   99,  100,   71],
       [ 81,   59,   90,  100]])

In [23]:
score = np.array([[1,2,3,4],[46,99,100,71],[81,59,90,100]])
score

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [24]:
a = score.argsort()
a, a[1, :]

(array([[0, 1, 2, 3],
        [0, 3, 1, 2],
        [1, 0, 2, 3]], dtype=int64), array([0, 3, 1, 2], dtype=int64))

In [25]:
a1 = score[:,score.argsort()[1,0]]
a2 = score[:,score.argsort()[1,1]]
a3 = score[:,score.argsort()[1,2]]
a4 = score[:,score.argsort()[1,3]]
np.vstack([a1, a2, a3, a4]).T

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])