#### 벡터화 연산

In [2]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)

In [5]:
z = np.zeros_like(x)
for i in range(10000):
    z[i] = x[i] + y[i]
    
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [7]:
(x + y)[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [8]:
x <= y

array([ True,  True,  True, ...,  True,  True,  True])

In [12]:
a = np.array([1, 2, 3, 4, 5])
idx = a % 2 == 0
idx, a[idx]

(array([False,  True, False,  True, False]), array([2, 4]))

In [14]:
b = np.array([1, 2, 3, 3, 5])

In [15]:
# np.all() : 모든 성분이 동일하면 True
np.all(a == b)

False

#### broadcasting
- Numpy에서는 서로 다른 크기를 가진 두 배열의 사칙연산도 지원
- 벡터(또는 행렬)끼리 덧셈 혹은 뺄셈을 하려면 두 벡터(또는 행렬)의 크기가 같아야 한다.
- 크기가 작은 배열은 자동으로 반복확장하여 크기가 큰 배열에 맞춘다.

In [18]:
a + 1

array([2, 3, 4, 5, 6])

In [26]:
c = np.arange(15).reshape(-1, 5)
print(a, c, sep="\n")

[1 2 3 4 5]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [55]:
d = a + c
d

array([[ 1,  3,  5,  7,  9],
       [ 6,  8, 10, 12, 14],
       [11, 13, 15, 17, 19]])

In [56]:
(a + c).mean()

10.0

In [77]:
np.random.shuffle(d)
d

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [ 6,  8, 10, 12, 14]])

In [78]:
d.mean(), d.sum(), d.std(), d.var()

(10.0, 150, 4.96655480858378, 24.666666666666668)

In [79]:
d.max(), d.min(), d.argmin(), d.argmax()

(19, 1, 0, 9)

#### 연산의 대상이 2차원 이상인 경우
- 어느 차원으로 계산을 할 지를 axis 인수를 사용하여 지시
- axis=0인 경우는 열 연산, axis=1인 경우는 행 연산
- 디폴트 값은 axis=0

In [82]:
d.sum(axis=0), d.sum(axis=1), d.sum(axis=-1)

(array([18, 24, 30, 36, 42]), array([25, 75, 50]), array([25, 75, 50]))

In [84]:
d.std(axis=0), d.std(axis=1)

(array([4.0824829, 4.0824829, 4.0824829, 4.0824829, 4.0824829]),
 array([2.82842712, 2.82842712, 2.82842712]))

#### 연습 문제 1¶
실수로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구한다.
1. 전체의 최댓값
2. 각 행의 합
3. 각 열의 평균

In [88]:
e = np.random.randint(1, 100, (5, 6))
e

array([[21, 92, 88, 79, 52, 85],
       [42, 74, 88, 74,  1, 17],
       [94,  9, 57, 46, 24, 97],
       [85, 29, 59, 13, 40, 48],
       [73, 49, 84, 79, 40, 18]])

In [89]:
e.max(), e.sum(axis=1), e.mean(axis=0)

(97,
 array([417, 296, 327, 274, 343]),
 array([63. , 50.6, 75.2, 58.2, 31.4, 53. ]))

#### practice
- 10^7개의 리스트에서 3과 5의 배수의 갯수를 찾는 시간

In [91]:
ls = []
for i in range(int(1E7)):
    ls.append(i)
na = np.array(ls)

In [96]:
%%time
count = 0
for i in range(len(ls)):
    if ls[i] % 3 == 0 or ls[i] % 5 == 0:
        count += 1
        
print(count)

4666667
Wall time: 2.56 s


In [100]:
%%time
count = len(na[(na % 3 == 0) | (na % 5 == 0)])
print(count)

4666667
Wall time: 253 ms


In [101]:
%%time
count = len(na[(na % 3 == 0) & (na % 5 == 0)])
print(count)

666667
Wall time: 181 ms


In [102]:
%%time
count = len(na[na % 15 == 0])
print(count)

666667
Wall time: 111 ms
