In [ ]:
def th_func(number):
    for idx in range(number):
        ls1.append(idx)

#### Numpy - make : 파이썬 list보다 빠름
- array
- reshape


In [4]:
import numpy as np

In [ ]:
### array
- ndim : 행렬의 차원
- shape : 행렬의 모양

In [5]:
array = np.array([0,1,2,3])
print(type(array), array)

<class 'numpy.ndarray'> [0 1 2 3]


In [ ]:
array = np.array([
    [0,1,2,3],
    [2,3],
    [4,5],
    
])

In [6]:
na = np.array(range(1,9))
na

array([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
na.reshape(2, 4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
rna = np.reshape(na, (4, 2))
rna

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [11]:
rna.T, rna.T.shape

(array([[1, 3, 5, 7],
        [2, 4, 6, 8]]), (2, 4))

In [13]:
data = np.array(range(5))

In [14]:
data[2] = 0

In [15]:
data

array([0, 1, 0, 3, 4])

In [17]:
data[3:] = 2
data

array([0, 1, 0, 2, 2])

In [20]:
data = np.array([range(3), range(3,6)])
data

array([[0, 1, 2],
       [3, 4, 5]])

In [21]:
data[1:,1:] = 10

In [22]:
data

array([[ 0,  1,  2],
       [ 3, 10, 10]])

In [29]:
z = np.zeros((2, 3, 4), dtype=int)

In [30]:
z

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [32]:
one = np.ones((2, 3, 4))
one

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [33]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
z

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [35]:
np.ones_like(z)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [36]:
one

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [37]:
np.zeros_like(one)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [40]:
np.empty((3,2))

array([[7.2e-322, 0.0e+000],
       [0.0e+000, 0.0e+000],
       [0.0e+000, 0.0e+000]])

In [42]:
print(range(1, 5, 2))


range(1, 5, 2)


In [44]:
size = int(1E6)
size

1000000

In [45]:
%timeit for x in range(size):x**2
%timeit for x in np.arange(size):x**2

447 ms ± 4.74 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
240 ms ± 4.17 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [46]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [47]:
np.arange(2, 10, 3)

array([2, 5, 8])

In [48]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [49]:
np.logspace(2, 4, 3)

array([  100.,  1000., 10000.])

In [68]:
np.random.seed(1)
rd = np.random.rand(10)
rd

array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
       1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01,
       3.96767474e-01, 5.38816734e-01])

In [54]:
rd.reshape(2, 5)

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ],
       [0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152]])

In [79]:
rdn = np.random.randn(2, 5)
rdn

array([[ 0.74055645, -0.9537006 , -0.26621851,  0.03261455, -1.37311732],
       [ 0.31515939,  0.84616065, -0.85951594,  0.35054598, -1.31228341]])

In [83]:
n = np.arange(5)
print(n, n.shape)

[0 1 2 3 4] (5,)


In [87]:
ls = []
for idx in range(5):
    ls.append(range(7)[idx:idx+3])
ls

[range(0, 3), range(1, 4), range(2, 5), range(3, 6), range(4, 7)]

In [88]:
np.vstack(ls)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [89]:
np.hstack(ls)

array([0, 1, 2, 1, 2, 3, 2, 3, 4, 3, 4, 5, 4, 5, 6])

In [92]:
ls = [list(range(7)[i:i+3]) for i in range(5)]
ls

[[0, 1, 2], [1, 2, 3], [2, 3, 4], [3, 4, 5], [4, 5, 6]]

In [93]:
ls = [1, 2, 3]
ls*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [94]:
ls = [i*3 for i in ls]
ls

[3, 6, 9]

In [95]:
na = np.array([1, 2, 3])
na

array([1, 2, 3])

In [97]:
print(na*3, na.shape)

[3 6 9] (3,)


In [98]:
na1 = np.array([1, 2, 3])
na2 = np.array([4, 5, 6])
na1 * na2

array([ 4, 10, 18])

In [99]:
na2 * na1

array([ 4, 10, 18])

In [103]:
na1 == 2, na2 > 5

(array([False,  True, False]), array([False, False,  True]))

In [104]:
na1 = np.array(range(10))
na1 % 3 == 0

array([ True, False, False,  True, False, False,  True, False, False,
        True])

In [106]:
na1 = np.arange(12)
na2 = na1.reshape(3, 4)
na3 = np.ones((3, 4), dtype = int)
print(na1)
print(na2)
print(na3)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [108]:
na4 = np.arange(4)
print(na4, na4.shape)

[0 1 2 3] (4,)


In [109]:
ls = []
size = int(10E7)
for data in range(size):
    ls.append(data)
len(ls)

100000000

In [119]:
ls2 = list(range(int(10)))
ls2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [111]:
la = np.arange(size)
len(la)

100000000

In [ ]:
count = 0
for idx in range(len(ls)):
    if (ls[i])